What went wrong:
When attempting to generate 3 unique digits, I called the random module directly.
I received "TypeError: 'module' object is not callable"